In [306]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go

In [307]:
data= pd.read_csv("/content/data-27.csv")
data.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1,inplace=True)
data

,datetime,open,high,low,close,volume
0,2018-01-01 00:00:00,13715.65,13818.55,12750.00,13135.00,6970.441076
1,2018-01-02 00:00:00,13135.00,14750.00,12890.02,14580.00,16359.347340
2,2018-01-03 00:00:00,14576.87,15473.49,14150.00,14749.97,19457.238601
3,2018-01-04 00:00:00,14710.00,15280.00,13918.04,14811.00,18783.876561
4,2018-01-05 00:00:00,14805.01,17118.13,14600.00,16579.00,22383.657333
...,...,...,...,...,...,...
2919,2023-12-28 05:30:00,43428.86,43787.57,42241.79,42563.76,35150.524850
2920,2023-12-29 05:30:00,42563.76,43111.00,41300.00,42066.95,42597.189120
2921,2023-12-30 05:30:00,42066.94,42612.32,41520.30,42140.28,22906.578180
2922,2023-12-31 05:30:00,42140.29,42899.00,41965.84,42283.58,23585.916030
2923,2024-01-01 05:30:00,42283.58,44184.10,42180.77,44179.55,27174.299030

# **Basic EDA**

In [308]:
data["close"].describe()

count     2924.000000
mean     18163.987353
std      15235.053085
min       3182.730000
25%       7202.960000
50%      10186.600000
75%      27321.242500
max      67525.830000
Name: close, dtype: float64

In [309]:
data["close"].std()

15235.053084894149

In [310]:
fig=go.Figure()
fig.add_trace(go.Scatter(x=data["datetime"], y=data["close"], name = "Closing Price", line = dict(color='blue', width=1)))
fig.update_layout(title=dict(text="CLOSING PRICE",x=0.45,y=0.9,font=dict(size=30)),yaxis_title="Closing Price",xaxis_title="Date")
fig.show()

# **PART 1**

In [311]:
data["SMA"]=data["close"].rolling(window=20).mean()
data

,datetime,open,high,low,close,volume,SMA
0,2018-01-01 00:00:00,13715.65,13818.55,12750.00,13135.00,6970.441076,NaN
1,2018-01-02 00:00:00,13135.00,14750.00,12890.02,14580.00,16359.347340,NaN
2,2018-01-03 00:00:00,14576.87,15473.49,14150.00,14749.97,19457.238601,NaN
3,2018-01-04 00:00:00,14710.00,15280.00,13918.04,14811.00,18783.876561,NaN
4,2018-01-05 00:00:00,14805.01,17118.13,14600.00,16579.00,22383.657333,NaN
...,...,...,...,...,...,...,...
2919,2023-12-28 05:30:00,43428.86,43787.57,42241.79,42563.76,35150.524850,42846.9030
2920,2023-12-29 05:30:00,42563.76,43111.00,41300.00,42066.95,42597.189120,42764.5705
2921,2023-12-30 05:30:00,42066.94,42612.32,41520.30,42140.28,22906.578180,42682.1090
2922,2023-12-31 05:30:00,42140.29,42899.00,41965.84,42283.58,23585.916030,42733.6180
2923,2024-01-01 05:30:00,42283.58,44184.10,42180.77,44179.55,27174.299030,42867.9760

In [312]:
data["EMA_20"]=data["close"].ewm(span=20).mean()
data["EMA_50"]=data["close"].ewm(span=50).mean()
data

,datetime,open,high,low,close,volume,SMA,EMA_20,EMA_50
0,2018-01-01 00:00:00,13715.65,13818.55,12750.00,13135.00,6970.441076,NaN,13135.000000,13135.000000
1,2018-01-02 00:00:00,13135.00,14750.00,12890.02,14580.00,16359.347340,NaN,13893.625000,13871.950000
2,2018-01-03 00:00:00,14576.87,15473.49,14150.00,14749.97,19457.238601,NaN,14208.069750,14176.406742
3,2018-01-04 00:00:00,14710.00,15280.00,13918.04,14811.00,18783.876561,NaN,14382.126391,14344.698286
4,2018-01-05 00:00:00,14805.01,17118.13,14600.00,16579.00,22383.657333,NaN,14913.531422,14828.007629
...,...,...,...,...,...,...,...,...,...
2919,2023-12-28 05:30:00,43428.86,43787.57,42241.79,42563.76,35150.524850,42846.9030,42561.562685,40117.559996
2920,2023-12-29 05:30:00,42563.76,43111.00,41300.00,42066.95,42597.189120,42764.5705,42514.456715,40194.006663
2921,2023-12-30 05:30:00,42066.94,42612.32,41520.30,42140.28,22906.578180,42682.1090,42478.820837,40270.331107
2922,2023-12-31 05:30:00,42140.29,42899.00,41965.84,42283.58,23585.916030,42733.6180,42460.226472,40349.282044
2923,2024-01-01 05:30:00,42283.58,44184.10,42180.77,44179.55,27174.299030,42867.9760,42623.971570,40499.488631

# **Part 2**

In [313]:
data["datetime"] = pd.to_datetime(data["datetime"])  ## changed the "datetime" column to datetime format as it was showing error that it is not in datetimeindex format...
data.set_index("datetime", inplace=True)  ### "datetime" is set as index to use resample....
data=data.resample("6ME").std()
data

,open,high,low,close,volume,SMA,EMA_20,EMA_50
datetime,,,,,,,,
2018-01-31,1953.749046,1943.772152,1832.733832,2015.271600,14332.753367,1673.858482,1615.462730,2095.625646
2018-07-31,1336.821118,1405.362631,1250.444304,1328.840791,13199.984664,1283.918815,1228.601848,1201.879990
2019-01-31,1410.051428,1415.048863,1401.626471,1407.786648,20559.136450,1383.408589,1342.525597,1155.467764
2019-07-31,2798.544476,2951.288993,2613.964158,2798.572026,25654.372489,2711.044541,2655.361520,2273.112387
2020-01-31,1311.889894,1353.239559,1282.404188,1312.245827,21872.694221,1202.311786,1183.960383,1015.167041
2020-07-31,1359.277338,1318.273343,1414.861895,1372.755043,48540.951884,1172.789434,1102.091652,778.042542
2021-01-31,8682.971108,9223.773238,8033.659677,8741.749329,35680.018105,7895.083377,7725.523673,6126.057590
2021-07-31,10068.198123,10191.642850,9879.054894,10029.363786,39449.411566,9469.083612,9097.900695,7606.618682
2022-01-31,7816.138630,7931.423141,7712.389159,7837.139102,17293.102390,7388.378596,7069.121042,6360.270273
2022-07-31,8864.850331,9001.222699,8781.261630,8890.239310,60278.992441,8253.250961,8126.021832,7083.762661
2023-01-31,2337.986400,2437.112329,2278.673728,2336.555334,109072.581747,2101.898046,2019.989626,1983.049021
2023-07-31,2748.377814,2744.383496,2766.344673,2736.763731,153890.555429,2598.526079,2582.886421,2773.760179
2024-01-31,6323.994354,6503.577272,6170.035830,6386.320742,17783.638776,5681.933991,5585.225295,4274.008913

In [314]:
print("The maximum volatility is with std.deviation:",data["close"].max())

The maximum volatility is with std.deviation: 10029.363786327744